---
apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  type: LoadBalancer
  selector:
    app: notification
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/my-repository/notification:latest
          ports:
            - containerPort: 8080